#!/bin/csh
#
# cbuild.csh: compile and link mbplot program
#
# David Barnes, May 2006
# Based on MXB "makeit" file and s2plot "cbuild.csh" script.
#
# $Id: makeit,v 1.4 2006/06/18 01:02:42 dbarnes Exp $
#
#
# usage: cbuild.csh

#setenv S2PLOT 1
#setenv S2PATH /Users/mbailes/swinburne/s2plot/



set dir=~/.mbplot


if !( -e $dir) then
	mkdir ~/.mbplot
	cp mbplot_general.cmd ~/.mbplot
endif

g++ -g -o mbplot -I. -I/home/dada/linux_64/pgplot/  mbplot.C plot.C dialog.C local_medians.C -L/home/dada/linux_64/pgplot/ -lcpgplot -lpgplot -L/usr/X11R6/lib -lX11 -lm -lgfortran -lpng -DCONFIG_DIR=\"$HOME/.mbplot/\"

exit

set target=distill

set source="mbplot.C plot.C dialog.C"
set object="mbplot.o plot.o dialog.o"

echo "Compiling source code file ${source} ..."
g++ -c -O -I${S2PATH} -I/home/dada/linux_64/pgplot/  $source

echo "Linking object file ${target}.o ..."
g++ -o $target ${object} -L${S2PATH} -ls2plot -L${S2PATH}/darwin-gnu-i386 -L/home/dada/linux_64/pgplot/ -lcpgplot -lpgplot -L/usr/X11R6/lib -lX11  -lm -lpng -lgfortran -lpng

echo "Cleaning up ..."
#rm -rf $object

echo "Done!"
